feat: docarray vectorstore
jupyterjazz/GPTCache pull request #1
Opened 2023-05-10 13:29 UTC by jupyterjazz

2023-05-11 14:12 UTC, JoanFM commented on gptcache/manager/vector_data/in_memory_exact_search.py
> +    def rebuild(self, ids=None):
why is this needed?

2023-05-14 08:33 UTC, jupyterjazz commented on gptcache/manager/vector_data/in_memory_exact_search.py
> +    def rebuild(self, ids=None):
This function is used to rebuild the index with a new data, represented by IDs. It's used when some number of deletions happen and the index needs to be updated to reflect the changes. But deletions doesn't affect InMemory index data structure so we can ignore it.

2023-05-14 08:36 UTC, jupyterjazz commented on gptcache/manager/vector_data/in_memory_exact_search.py
> +    def rebuild(self, ids=None):
We could also add this to our indices, hnsw will definitely benefit from it

2023-05-15 12:21 UTC, samsja requested changes
we need to keep the single quote as it was originally

2023-05-15 12:22 UTC, samsja requested changes
we need to keep the single quote as it was originally

2023-05-16 11:43 UTC, merged